// 개신교 정경 66권: (book_id, english, korean, bolls_code, chapter_count)
// book_id는 전통적 순서 (1=Genesis, 66=Revelation)
module.exports = [
  { id:  1, en: "Genesis",         ko: "창세기",       bolls: "GEN", chapters: 50 },
  { id:  2, en: "Exodus",          ko: "출애굽기",     bolls: "EXO", chapters: 40 },
  { id:  3, en: "Leviticus",       ko: "레위기",       bolls: "LEV", chapters: 27 },
  { id:  4, en: "Numbers",         ko: "민수기",       bolls: "NUM", chapters: 36 },
  { id:  5, en: "Deuteronomy",     ko: "신명기",       bolls: "DEU", chapters: 34 },
  { id:  6, en: "Joshua",          ko: "여호수아",     bolls: "JOS", chapters: 24 },
  { id:  7, en: "Judges",          ko: "사사기",       bolls: "JDG", chapters: 21 },
  { id:  8, en: "Ruth",            ko: "룻기",         bolls: "RUT", chapters:  4 },
  { id:  9, en: "1 Samuel",        ko: "사무엘상",     bolls: "1SA", chapters: 31 },
  { id: 10, en: "2 Samuel",        ko: "사무엘하",     bolls: "2SA", chapters: 24 },
  { id: 11, en: "1 Kings",         ko: "열왕기상",     bolls: "1KI", chapters: 22 },
  { id: 12, en: "2 Kings",         ko: "열왕기하",     bolls: "2KI", chapters: 25 },
  { id: 13, en: "1 Chronicles",    ko: "역대상",       bolls: "1CH", chapters: 29 },
  { id: 14, en: "2 Chronicles",    ko: "역대하",       bolls: "2CH", chapters: 36 },
  { id: 15, en: "Ezra",            ko: "에스라",       bolls: "EZR", chapters: 10 },
  { id: 16, en: "Nehemiah",        ko: "느헤미야",     bolls: "NEH", chapters: 13 },
  { id: 17, en: "Esther",          ko: "에스더",       bolls: "EST", chapters: 10 },
  { id: 18, en: "Job",             ko: "욥기",         bolls: "JOB", chapters: 42 },
  { id: 19, en: "Psalms",          ko: "시편",         bolls: "PSA", chapters: 150 },
  { id: 20, en: "Proverbs",        ko: "잠언",         bolls: "PRO", chapters: 31 },
  { id: 21, en: "Ecclesiastes",    ko: "전도서",       bolls: "ECC", chapters: 12 },
  { id: 22, en: "Song of Solomon", ko: "아가",         bolls: "SNG", chapters:  8 },
  { id: 23, en: "Isaiah",          ko: "이사야",       bolls: "ISA", chapters: 66 },
  { id: 24, en: "Jeremiah",        ko: "예레미야",     bolls: "JER", chapters: 52 },
  { id: 25, en: "Lamentations",    ko: "예레미야애가", bolls: "LAM", chapters:  5 },
  { id: 26, en: "Ezekiel",         ko: "에스겔",       bolls: "EZK", chapters: 48 },
  { id: 27, en: "Daniel",          ko: "다니엘",       bolls: "DAN", chapters: 12 },
  { id: 28, en: "Hosea",           ko: "호세아",       bolls: "HOS", chapters: 14 },
  { id: 29, en: "Joel",            ko: "요엘",         bolls: "JOL", chapters:  3 },
  { id: 30, en: "Amos",            ko: "아모스",       bolls: "AMO", chapters:  9 },
  { id: 31, en: "Obadiah",         ko: "오바댜",       bolls: "OBA", chapters:  1 },
  { id: 32, en: "Jonah",           ko: "요나",         bolls: "JON", chapters:  4 },
  { id: 33, en: "Micah",           ko: "미가",         bolls: "MIC", chapters:  7 },
  { id: 34, en: "Nahum",           ko: "나훔",         bolls: "NAM", chapters:  3 },
  { id: 35, en: "Habakkuk",        ko: "하박국",       bolls: "HAB", chapters:  3 },
  { id: 36, en: "Zephaniah",       ko: "스바냐",       bolls: "ZEP", chapters:  3 },
  { id: 37, en: "Haggai",          ko: "학개",         bolls: "HAG", chapters:  2 },
  { id: 38, en: "Zechariah",       ko: "스가랴",       bolls: "ZEC", chapters: 14 },
  { id: 39, en: "Malachi",         ko: "말라기",       bolls: "MAL", chapters:  4 },
  { id: 40, en: "Matthew",         ko: "마태복음",     bolls: "MAT", chapters: 28 },
  { id: 41, en: "Mark",            ko: "마가복음",     bolls: "MRK", chapters: 16 },
  { id: 42, en: "Luke",            ko: "누가복음",     bolls: "LUK", chapters: 24 },
  { id: 43, en: "John",            ko: "요한복음",     bolls: "JHN", chapters: 21 },
  { id: 44, en: "Acts",            ko: "사도행전",     bolls: "ACT", chapters: 28 },
  { id: 45, en: "Romans",          ko: "로마서",       bolls: "ROM", chapters: 16 },
  { id: 46, en: "1 Corinthians",   ko: "고린도전서",   bolls: "1CO", chapters: 16 },
  { id: 47, en: "2 Corinthians",   ko: "고린도후서",   bolls: "2CO", chapters: 13 },
  { id: 48, en: "Galatians",       ko: "갈라디아서",   bolls: "GAL", chapters:  6 },
  { id: 49, en: "Ephesians",       ko: "에베소서",     bolls: "EPH", chapters:  6 },
  { id: 50, en: "Philippians",     ko: "빌립보서",     bolls: "PHP", chapters:  4 },
  { id: 51, en: "Colossians",      ko: "골로새서",     bolls: "COL", chapters:  4 },
  { id: 52, en: "1 Thessalonians", ko: "데살로니가전서", bolls: "1TH", chapters:  5 },
  { id: 53, en: "2 Thessalonians", ko: "데살로니가후서", bolls: "2TH", chapters:  3 },
  { id: 54, en: "1 Timothy",       ko: "디모데전서",   bolls: "1TI", chapters:  6 },
  { id: 55, en: "2 Timothy",       ko: "디모데후서",   bolls: "2TI", chapters:  4 },
  { id: 56, en: "Titus",           ko: "디도서",       bolls: "TIT", chapters:  3 },
  { id: 57, en: "Philemon",        ko: "빌레몬서",     bolls: "PHM", chapters:  1 },
  { id: 58, en: "Hebrews",         ko: "히브리서",     bolls: "HEB", chapters: 13 },
  { id: 59, en: "James",           ko: "야고보서",     bolls: "JAS", chapters:  5 },
  { id: 60, en: "1 Peter",         ko: "베드로전서",   bolls: "1PE", chapters:  5 },
  { id: 61, en: "2 Peter",         ko: "베드로후서",   bolls: "2PE", chapters:  3 },
  { id: 62, en: "1 John",          ko: "요한일서",     bolls: "1JN", chapters:  5 },
  { id: 63, en: "2 John",          ko: "요한이서",     bolls: "2JN", chapters:  1 },
  { id: 64, en: "3 John",          ko: "요한삼서",     bolls: "3JN", chapters:  1 },
  { id: 65, en: "Jude",            ko: "유다서",       bolls: "JUD", chapters:  1 },
  { id: 66, en: "Revelation",      ko: "요한계시록",   bolls: "REV", chapters: 22 },
];
